server:
  port: '8080'

spring:
  application:
    name: device-management

  datasource:
    url: jdbc:h2:file:~/sensors-device-management-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    username: sa
    password: '123'
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false